WORLD_SCALE: int = 32
OBJECT_SCALE: int = WORLD_SCALE // 2
SPRITE_SCALE: int = WORLD_SCALE * 2

ANIMATION_NUM_FRAMES: int = 4

RESOLUTION_X: int = WORLD_SCALE * 10
RESOLUTION_Y: int = int(RESOLUTION_X * 0.75)

# objects row offsets
FOOD_OBJ: int = 0
DANGER_OBJ: int = 1
BONUS_OBJ: int = 2
WEAPON_OBJ: int = 3
MAX_OBJECT_TYPE: int = WEAPON_OBJ

SPRITE_CLOTHES_COLORS = ['#ff0000', '#800000', '#bf0000']
